### ISSUE TITLE
Question regarding installer

### ISSUE THREAD

**Issue by Dfmaaa** [Soviet-Linux/revolution-installer#1]
I came here from https://docs.sovietlinux.ml/installer and I thought it would be an ISO, what does executing bin/revolution actually do? Do I need to have something installed before running it?(except make and gcc)

**Comment by TheHolyTachanka** [comment]
If you want a iso you can download it from https://sovietlinux.ml/

**Comment by PKD667** [comment]
The installer is installing Soviet from another system. And the iso will include this installer  , so to install Soviet you will have to boot the iso and type revolution (or revolution-installer I don't know what will be the final name for the binary) and it will install Soviet on a drive or a partition . It's like archinstall or even void-installer

**Comment by Dfmaaa** [comment]
So, the installer asks the user for the location of another partition? And then it will do everything on that? I can do this from the terminal of my linux distro? How will I use soviet-linux? Will I have to add it to grub manually?

**Comment by PKD667** [comment]
Yea it will ask you for partitioning and it will install grub , it will even ask you if you want to tweak your kernel . But for now it isn't ready because it uses the cccp and it isn't fully working

**Comment by Dfmaaa** [comment]
oh

**Comment by Dfmaaa** [comment]
also

**Comment by Dfmaaa** [comment]
[](url
![soverror](https://user-images.githubusercontent.com/82197472/166154879-6edf0c77-e679-4cdb-a192-f8845aad44c0.png)
)
was trying to use the torrent file on the main page

**Comment by Dfmaaa** [comment]
pain

**Comment by PKD667** [comment]
Oh I know this issue , but I can't fix it because I don't have a computer rn . The problem is caused by /etc/fstab. You can edit it, you need to set the root mount (/) to the live cd fs. 
PS: join our Discord if you want the latest news about Soviet

**Comment by PKD667** [comment]
We need c programmers

**Comment by Dfmaaa** [comment]
I can code in C!

**Comment by PKD667** [comment]
If you can contribute to the project It would be great !

**Comment by Dfmaaa** [comment]
:D I'll see the code today!
