### ISSUE TITLE
Optimisation's

### ISSUE THREAD

**Issue by 0bishop** [Soviet-Linux/revolution-installer#14]
**What I do  2:**

    - I inprove optimisation and syntax.  
    - Aborting 100K useless inclusion.  
    - Erasing the fucking function "scanf" with my own (secure).  
    - Adding colors in the main.c (util.h).  
    - I put forward the revolution.h (adding the defines, includes, and adding ifndef define in order to skip useless double inclusion of libs.  
[src.zip](https://github.com/Soviet-Linux/revolution-installer/files/9579306/src.zip)

**Comment by AntaresMKII** [comment]
merged the changes
